
postgres:
  host: "postgres"
  port: "5432"
  password: "example"
  user: "postgres"
  database: "postgres"
stream_ingester:
  bind_address: ":1935"
web:
  bind_address: ":8933"
api:
  users:
    bind_address: ":39510"
auth:
  signing_secret: "changeThisInProd"
  ident: "https://mydomain.url" # Token Issuer Ident
  token_duration: "6h"