
postgres:
  host: "postgres"
  port: "5432"
  password: "example"
  user: "postgres"
  database: "postgres"
stream_ingester:
  bind_address: ":1935"
web:
  bind_address: ":8933"
api:
  users:
    bind_address: ":39510"
